name: Update URLs
run-name: Updating some URLs to be valid URLs
on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 * * * *'
jobs:
  Update-URLs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script to update URLs
        run: |
          chmod +x ./yt_live.sh
          ./yt_live.sh
        shell: bash
        working-directory: ./scripts
      - name: Commit changes
        run: |
          git config --global user.name 'arman1371'
          git config --global user.email 'arman1371@users.noreply.github.com'
          git add ir.m3u
          git commit -am "Automated commit for updated URLs"
          git push